
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type EggOpenWeightTb struct {
    _dataMap map[int32]*IEggOpenWeight
    _dataList []*IEggOpenWeight
}

func NewEggOpenWeightTb(_buf []map[string]interface{}) (*EggOpenWeightTb, error) {
    _dataList := make([]*IEggOpenWeight, 0, len(_buf))
    dataMap := make(map[int32]*IEggOpenWeight)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIEggOpenWeight(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &EggOpenWeightTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *EggOpenWeightTb) GetDataMap() map[int32]*IEggOpenWeight {
    return table._dataMap
}

func (table *EggOpenWeightTb) GetDataList() []*IEggOpenWeight {
    return table._dataList
}

func (table *EggOpenWeightTb) Get(key int32) *IEggOpenWeight {
    return table._dataMap[key]
}


