
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type EggPart2Tb struct {
    _dataMap map[int32]*IEggPart2
    _dataList []*IEggPart2
}

func NewEggPart2Tb(_buf []map[string]interface{}) (*EggPart2Tb, error) {
    _dataList := make([]*IEggPart2, 0, len(_buf))
    dataMap := make(map[int32]*IEggPart2)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIEggPart2(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &EggPart2Tb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *EggPart2Tb) GetDataMap() map[int32]*IEggPart2 {
    return table._dataMap
}

func (table *EggPart2Tb) GetDataList() []*IEggPart2 {
    return table._dataList
}

func (table *EggPart2Tb) Get(key int32) *IEggPart2 {
    return table._dataMap[key]
}


