
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type EggPart3Tb struct {
    _dataMap map[int32]*IEggPart3
    _dataList []*IEggPart3
}

func NewEggPart3Tb(_buf []map[string]interface{}) (*EggPart3Tb, error) {
    _dataList := make([]*IEggPart3, 0, len(_buf))
    dataMap := make(map[int32]*IEggPart3)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIEggPart3(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &EggPart3Tb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *EggPart3Tb) GetDataMap() map[int32]*IEggPart3 {
    return table._dataMap
}

func (table *EggPart3Tb) GetDataList() []*IEggPart3 {
    return table._dataList
}

func (table *EggPart3Tb) Get(key int32) *IEggPart3 {
    return table._dataMap[key]
}


