
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 裸
     */
    EggPartType_Part1 = 1;
    /**
     * 挂件
     */
    EggPartType_Part2 = 2;
    /**
     * 背光
     */
    EggPartType_Part3 = 3;
)

