
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type EggScoreTb struct {
    _dataMap map[int32]*IEggScore
    _dataList []*IEggScore
}

func NewEggScoreTb(_buf []map[string]interface{}) (*EggScoreTb, error) {
    _dataList := make([]*IEggScore, 0, len(_buf))
    dataMap := make(map[int32]*IEggScore)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIEggScore(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &EggScoreTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *EggScoreTb) GetDataMap() map[int32]*IEggScore {
    return table._dataMap
}

func (table *EggScoreTb) GetDataList() []*IEggScore {
    return table._dataList
}

func (table *EggScoreTb) Get(key int32) *IEggScore {
    return table._dataMap[key]
}


