
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type EggTb struct {
    _dataMap map[int32]*IEgg
    _dataList []*IEgg
}

func NewEggTb(_buf []map[string]interface{}) (*EggTb, error) {
    _dataList := make([]*IEgg, 0, len(_buf))
    dataMap := make(map[int32]*IEgg)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIEgg(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &EggTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *EggTb) GetDataMap() map[int32]*IEgg {
    return table._dataMap
}

func (table *EggTb) GetDataList() []*IEgg {
    return table._dataList
}

func (table *EggTb) Get(key int32) *IEgg {
    return table._dataMap[key]
}


