
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type ErrorTb struct {
    _dataMap map[int32]*IError
    _dataList []*IError
}

func NewErrorTb(_buf []map[string]interface{}) (*ErrorTb, error) {
    _dataList := make([]*IError, 0, len(_buf))
    dataMap := make(map[int32]*IError)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIError(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &ErrorTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *ErrorTb) GetDataMap() map[int32]*IError {
    return table._dataMap
}

func (table *ErrorTb) GetDataList() []*IError {
    return table._dataList
}

func (table *ErrorTb) Get(key int32) *IError {
    return table._dataMap[key]
}


