
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 高级
     */
    GlobalQuality_Ordinary = 1;
    /**
     * 稀有
     */
    GlobalQuality_Rare = 2;
    /**
     * 史诗
     */
    GlobalQuality_Epic = 3;
    /**
     * 传说
     */
    GlobalQuality_Legendary = 4;
    /**
     * 神话
     */
    GlobalQuality_Mythic = 5;
)

