
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GuideListTb struct {
    _dataMap map[int32]*IGuideList
    _dataList []*IGuideList
}

func NewGuideListTb(_buf []map[string]interface{}) (*GuideListTb, error) {
    _dataList := make([]*IGuideList, 0, len(_buf))
    dataMap := make(map[int32]*IGuideList)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIGuideList(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GuideListTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GuideListTb) GetDataMap() map[int32]*IGuideList {
    return table._dataMap
}

func (table *GuideListTb) GetDataList() []*IGuideList {
    return table._dataList
}

func (table *GuideListTb) Get(key int32) *IGuideList {
    return table._dataMap[key]
}


