
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type GuideTb struct {
    _dataMap map[int32]*IGuide
    _dataList []*IGuide
}

func NewGuideTb(_buf []map[string]interface{}) (*GuideTb, error) {
    _dataList := make([]*IGuide, 0, len(_buf))
    dataMap := make(map[int32]*IGuide)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIGuide(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &GuideTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *GuideTb) GetDataMap() map[int32]*IGuide {
    return table._dataMap
}

func (table *GuideTb) GetDataList() []*IGuide {
    return table._dataList
}

func (table *GuideTb) Get(key int32) *IGuide {
    return table._dataMap[key]
}


