
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type IEgg struct {
    Id int32
    PartType int32
    PartName string
    Quality int32
    EggScore float64
    PartIcon string
}

const TypeId_IEgg = 2244348

func (*IEgg) GetTypeId() int32 {
    return 2244348
}

func NewIEgg(_buf map[string]interface{}) (_v *IEgg, err error) {
    _v = &IEgg{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["partType"].(float64); !_ok_ { err = errors.New("partType error"); return }; _v.PartType = int32(_tempNum_) }
    { var _ok_ bool; if _v.PartName, _ok_ = _buf["partName"].(string); !_ok_ { err = errors.New("partName error"); return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["quality"].(float64); !_ok_ { err = errors.New("quality error"); return }; _v.Quality = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["eggScore"].(float64); !_ok_ { err = errors.New("eggScore error"); return }; _v.EggScore = float64(_tempNum_) }
    { var _ok_ bool; if _v.PartIcon, _ok_ = _buf["partIcon"].(string); !_ok_ { err = errors.New("partIcon error"); return } }
    return
}

