
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type IEggOpenWeight struct {
    Id int32
    GroupId int32
    ItemType int32
    ArticleId int32
    ArticleNum int32
    Weight int32
}

const TypeId_IEggOpenWeight = 1134658942

func (*IEggOpenWeight) GetTypeId() int32 {
    return 1134658942
}

func NewIEggOpenWeight(_buf map[string]interface{}) (_v *IEggOpenWeight, err error) {
    _v = &IEggOpenWeight{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["groupId"].(float64); !_ok_ { err = errors.New("groupId error"); return }; _v.GroupId = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["itemType"].(float64); !_ok_ { err = errors.New("itemType error"); return }; _v.ItemType = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["articleId"].(float64); !_ok_ { err = errors.New("articleId error"); return }; _v.ArticleId = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["articleNum"].(float64); !_ok_ { err = errors.New("articleNum error"); return }; _v.ArticleNum = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["weight"].(float64); !_ok_ { err = errors.New("weight error"); return }; _v.Weight = int32(_tempNum_) }
    return
}

