
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type IHelp struct {
    Id int32
    Desc string
}

const TypeId_IHelp = 69662506

func (*IHelp) GetTypeId() int32 {
    return 69662506
}

func NewIHelp(_buf map[string]interface{}) (_v *IHelp, err error) {
    _v = &IHelp{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; if _v.Desc, _ok_ = _buf["desc"].(string); !_ok_ { err = errors.New("desc error"); return } }
    return
}

