
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type IItem struct {
    Id int32
    Name string
    Quality int32
    Type int32
    Icon string
    Cmd string
    Param string
    UseType int32
}

const TypeId_IItem = 69706492

func (*IItem) GetTypeId() int32 {
    return 69706492
}

func NewIItem(_buf map[string]interface{}) (_v *IItem, err error) {
    _v = &IItem{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; if _v.Name, _ok_ = _buf["name"].(string); !_ok_ { err = errors.New("name error"); return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["quality"].(float64); !_ok_ { err = errors.New("quality error"); return }; _v.Quality = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["type"].(float64); !_ok_ { err = errors.New("type error"); return }; _v.Type = int32(_tempNum_) }
    { var _ok_ bool; if _v.Icon, _ok_ = _buf["icon"].(string); !_ok_ { err = errors.New("icon error"); return } }
    { var _ok_ bool; if _v.Cmd, _ok_ = _buf["cmd"].(string); !_ok_ { err = errors.New("cmd error"); return } }
    { var _ok_ bool; if _v.Param, _ok_ = _buf["param"].(string); !_ok_ { err = errors.New("param error"); return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["useType"].(float64); !_ok_ { err = errors.New("useType error"); return }; _v.UseType = int32(_tempNum_) }
    return
}

