
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type IPassPortRewardTb struct {
    Id int32
    Lv int32
    Exp int32
    OrdinaryReward *GlobalItemData
    DeluxeReward *GlobalItemData
    Issue int32
}

const TypeId_IPassPortRewardTb = 161279672

func (*IPassPortRewardTb) GetTypeId() int32 {
    return 161279672
}

func NewIPassPortRewardTb(_buf map[string]interface{}) (_v *IPassPortRewardTb, err error) {
    _v = &IPassPortRewardTb{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["lv"].(float64); !_ok_ { err = errors.New("lv error"); return }; _v.Lv = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["exp"].(float64); !_ok_ { err = errors.New("exp error"); return }; _v.Exp = int32(_tempNum_) }
    { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _buf["ordinaryReward"].(map[string]interface{}); !_ok_ { err = errors.New("ordinaryReward error"); return }; if _v.OrdinaryReward, err = NewGlobalItemData(_x_); err != nil { return } }
    { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _buf["deluxeReward"].(map[string]interface{}); !_ok_ { err = errors.New("deluxeReward error"); return }; if _v.DeluxeReward, err = NewGlobalItemData(_x_); err != nil { return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["issue"].(float64); !_ok_ { err = errors.New("issue error"); return }; _v.Issue = int32(_tempNum_) }
    return
}

