
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type IPassPortIssueTb struct {
    Id int32
    Desc string
    StartTime int32
    EndTime int32
    Issue int32
    DeluxeRewardBuy int32
    Banner string
}

const TypeId_IPassPortIssueTb = 35469580

func (*IPassPortIssueTb) GetTypeId() int32 {
    return 35469580
}

func NewIPassPortIssueTb(_buf map[string]interface{}) (_v *IPassPortIssueTb, err error) {
    _v = &IPassPortIssueTb{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; if _v.Desc, _ok_ = _buf["desc"].(string); !_ok_ { err = errors.New("desc error"); return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["startTime"].(float64); !_ok_ { err = errors.New("startTime error"); return }; _v.StartTime = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["endTime"].(float64); !_ok_ { err = errors.New("endTime error"); return }; _v.EndTime = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["issue"].(float64); !_ok_ { err = errors.New("issue error"); return }; _v.Issue = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["deluxeRewardBuy"].(float64); !_ok_ { err = errors.New("deluxeRewardBuy error"); return }; _v.DeluxeRewardBuy = int32(_tempNum_) }
    { var _ok_ bool; if _v.Banner, _ok_ = _buf["banner"].(string); !_ok_ { err = errors.New("banner error"); return } }
    return
}

