
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ISceneInfo struct {
    Id string
}

const TypeId_ISceneInfo = -2022560495

func (*ISceneInfo) GetTypeId() int32 {
    return -2022560495
}

func NewISceneInfo(_buf map[string]interface{}) (_v *ISceneInfo, err error) {
    _v = &ISceneInfo{}
    { var _ok_ bool; if _v.Id, _ok_ = _buf["id"].(string); !_ok_ { err = errors.New("id error"); return } }
    return
}

