
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ISignTb struct {
    Id int32
    Reward *GlobalItemData
}

const TypeId_ISignTb = -1455341900

func (*ISignTb) GetTypeId() int32 {
    return -1455341900
}

func NewISignTb(_buf map[string]interface{}) (_v *ISignTb, err error) {
    _v = &ISignTb{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _buf["reward"].(map[string]interface{}); !_ok_ { err = errors.New("reward error"); return }; if _v.Reward, err = NewGlobalItemData(_x_); err != nil { return } }
    return
}

