
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ITaskType struct {
    Id int32
    TaskName string
    Desc string
    GotoType int32
    Goto string
}

const TypeId_ITaskType = 854325704

func (*ITaskType) GetTypeId() int32 {
    return 854325704
}

func NewITaskType(_buf map[string]interface{}) (_v *ITaskType, err error) {
    _v = &ITaskType{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; if _v.TaskName, _ok_ = _buf["taskName"].(string); !_ok_ { err = errors.New("taskName error"); return } }
    { var _ok_ bool; if _v.Desc, _ok_ = _buf["desc"].(string); !_ok_ { err = errors.New("desc error"); return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["gotoType"].(float64); !_ok_ { err = errors.New("gotoType error"); return }; _v.GotoType = int32(_tempNum_) }
    { var _ok_ bool; if _v.Goto, _ok_ = _buf["goto"].(string); !_ok_ { err = errors.New("goto error"); return } }
    return
}

