
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 普通道具
     */
    ItemType_Item = 1;
    /**
     * 宝箱
     */
    ItemType_Box = 2;
)

