
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type ItemTb struct {
    _dataMap map[int32]*IItem
    _dataList []*IItem
}

func NewItemTb(_buf []map[string]interface{}) (*ItemTb, error) {
    _dataList := make([]*IItem, 0, len(_buf))
    dataMap := make(map[int32]*IItem)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIItem(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &ItemTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *ItemTb) GetDataMap() map[int32]*IItem {
    return table._dataMap
}

func (table *ItemTb) GetDataList() []*IItem {
    return table._dataList
}

func (table *ItemTb) Get(key int32) *IItem {
    return table._dataMap[key]
}


