
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type PassPortIssueTb struct {
    _dataMap map[int32]*IPassPortIssueTb
    _dataList []*IPassPortIssueTb
}

func NewPassPortIssueTb(_buf []map[string]interface{}) (*PassPortIssueTb, error) {
    _dataList := make([]*IPassPortIssueTb, 0, len(_buf))
    dataMap := make(map[int32]*IPassPortIssueTb)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIPassPortIssueTb(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &PassPortIssueTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *PassPortIssueTb) GetDataMap() map[int32]*IPassPortIssueTb {
    return table._dataMap
}

func (table *PassPortIssueTb) GetDataList() []*IPassPortIssueTb {
    return table._dataList
}

func (table *PassPortIssueTb) Get(key int32) *IPassPortIssueTb {
    return table._dataMap[key]
}


