
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type PassPortRewardTb struct {
    _dataMap map[int32]*IPassPortRewardTb
    _dataList []*IPassPortRewardTb
}

func NewPassPortRewardTb(_buf []map[string]interface{}) (*PassPortRewardTb, error) {
    _dataList := make([]*IPassPortRewardTb, 0, len(_buf))
    dataMap := make(map[int32]*IPassPortRewardTb)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIPassPortRewardTb(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &PassPortRewardTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *PassPortRewardTb) GetDataMap() map[int32]*IPassPortRewardTb {
    return table._dataMap
}

func (table *PassPortRewardTb) GetDataList() []*IPassPortRewardTb {
    return table._dataList
}

func (table *PassPortRewardTb) Get(key int32) *IPassPortRewardTb {
    return table._dataMap[key]
}


