
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type RedPointTb struct {
    _dataMap map[string]*IRedPoint
    _dataList []*IRedPoint
}

func NewRedPointTb(_buf []map[string]interface{}) (*RedPointTb, error) {
    _dataList := make([]*IRedPoint, 0, len(_buf))
    dataMap := make(map[string]*IRedPoint)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIRedPoint(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &RedPointTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *RedPointTb) GetDataMap() map[string]*IRedPoint {
    return table._dataMap
}

func (table *RedPointTb) GetDataList() []*IRedPoint {
    return table._dataList
}

func (table *RedPointTb) Get(key string) *IRedPoint {
    return table._dataMap[key]
}


