
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type ReSignTb struct {
    _dataMap map[int32]*IReSignTb
    _dataList []*IReSignTb
}

func NewReSignTb(_buf []map[string]interface{}) (*ReSignTb, error) {
    _dataList := make([]*IReSignTb, 0, len(_buf))
    dataMap := make(map[int32]*IReSignTb)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIReSignTb(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &ReSignTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *ReSignTb) GetDataMap() map[int32]*IReSignTb {
    return table._dataMap
}

func (table *ReSignTb) GetDataList() []*IReSignTb {
    return table._dataList
}

func (table *ReSignTb) Get(key int32) *IReSignTb {
    return table._dataMap[key]
}


