
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SceneInfo struct {
    _dataMap map[string]*ISceneInfo
    _dataList []*ISceneInfo
}

func NewSceneInfo(_buf []map[string]interface{}) (*SceneInfo, error) {
    _dataList := make([]*ISceneInfo, 0, len(_buf))
    dataMap := make(map[string]*ISceneInfo)

    for _, _ele_ := range _buf {
        if _v, err2 := NewISceneInfo(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SceneInfo{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SceneInfo) GetDataMap() map[string]*ISceneInfo {
    return table._dataMap
}

func (table *SceneInfo) GetDataList() []*ISceneInfo {
    return table._dataList
}

func (table *SceneInfo) Get(key string) *ISceneInfo {
    return table._dataMap[key]
}


