
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 每日
     */
    ShopType_Daily = 1;
    /**
     * 普通
     */
    ShopType_Ordinary = 2;
    /**
     * 钻石
     */
    ShopType_Diamond = 3;
    /**
     * 特殊
     */
    ShopType_Special = 4;
)

