
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type SignTb struct {
    _dataMap map[int32]*ISignTb
    _dataList []*ISignTb
}

func NewSignTb(_buf []map[string]interface{}) (*SignTb, error) {
    _dataList := make([]*ISignTb, 0, len(_buf))
    dataMap := make(map[int32]*ISignTb)

    for _, _ele_ := range _buf {
        if _v, err2 := NewISignTb(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &SignTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *SignTb) GetDataMap() map[int32]*ISignTb {
    return table._dataMap
}

func (table *SignTb) GetDataList() []*ISignTb {
    return table._dataList
}

func (table *SignTb) Get(key int32) *ISignTb {
    return table._dataMap[key]
}


