
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TaskTypeTb struct {
    _dataMap map[int32]*ITaskType
    _dataList []*ITaskType
}

func NewTaskTypeTb(_buf []map[string]interface{}) (*TaskTypeTb, error) {
    _dataList := make([]*ITaskType, 0, len(_buf))
    dataMap := make(map[int32]*ITaskType)

    for _, _ele_ := range _buf {
        if _v, err2 := NewITaskType(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TaskTypeTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TaskTypeTb) GetDataMap() map[int32]*ITaskType {
    return table._dataMap
}

func (table *TaskTypeTb) GetDataList() []*ITaskType {
    return table._dataList
}

func (table *TaskTypeTb) Get(key int32) *ITaskType {
    return table._dataMap[key]
}


