
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type UnlockTb struct {
    _dataMap map[int32]*IUnlock
    _dataList []*IUnlock
}

func NewUnlockTb(_buf []map[string]interface{}) (*UnlockTb, error) {
    _dataList := make([]*IUnlock, 0, len(_buf))
    dataMap := make(map[int32]*IUnlock)

    for _, _ele_ := range _buf {
        if _v, err2 := NewIUnlock(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &UnlockTb{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *UnlockTb) GetDataMap() map[int32]*IUnlock {
    return table._dataMap
}

func (table *UnlockTb) GetDataList() []*IUnlock {
    return table._dataList
}

func (table *UnlockTb) Get(key int32) *IUnlock {
    return table._dataMap[key]
}


