// Code generated by error-gen. DO NOT EDIT.
package constant

const (
    NetWorkError = 400                           // 网络错误
    ServerBusy = -3                              // 服务器繁忙
    TooManyRequests = -2                         // 请求太频繁
    UnknownError = -1                            // 未知错误
    OK = 0                                       // 成功
    ParametersInvalid = 1                        // 参数有误
    RDBError = 2                                 // 数据库异常
    DatabaseError = 3                            // 数据库异常
    JsonMarshalError = 4                         // 数据库数据解析异常
    JsonUnmarshalError = 5                       // 数据库数据解析异常
    TokenInvalid = 6                             // Token无效
    TokenGenerateFail = 7                        // 生成toke失败
    Unauthorized = 8                             // 用户还没登录
    LoggedInOnAnotherDevice = 9                  // 你在其他设备上登录了
    LoginExpired = 10                            // 登录已过期，请重新登录
    ItemNotFound = 11                            // 道具找不到
    ItemNotEnough = 12                           // 道具不足
    DiamondNotEnough = 13                        // 钻石不足
    MinionsNotFound = 14                         // 宠物找不到
    MinionsNotEnough = 15                        // 宠物数量不足
    ShopNotFound = 16                            // 商品没有找到
    PurchaseRestrictions = 17                    // 购买限制
    RewardClaimed = 18                           // 奖励已领取
    PermissionDenied = 19                        // 无权执行
    BattleAlreadyStarted = 20                    // 已经开始战斗
    BattleMemberNotEnough = 21                   // 人数不足，房间解散
    BattleAlreadyDismiss = 22                    // 房间已经解散
    BattleDataError = 23                         // 战斗数据错误
    BattleBetFailItemNotEnough = 24              // 下注失败，道具不足
    BattleYouNotInRound = 25                     // 你不在本回合
    NotQualified = 26                            // 不符合入场资格
    AlreadyJoinOtherBattle = 27                  // 已报名其他战场
    BattleRegistrationFull = 28                  // 报名人数已满
    RegisteredUsers = 29                         // 最近一小时注册的用户数量: {1}
    BattleVictory = 1000                         // 你在刚刚的{1}取得胜利获得奖励{2} <img src='ui://item/gofen'/>
    BattleFailure = 1001                         // 你在刚刚的{1}遗憾落败
    ShopRefresh = 1002                           // 是否花费{1} <img src='ui://item/zs02'/>刷新？
    ShopBuy = 1003                               // 是否花费{1} <img src='ui://item/zs02'/>购买？{2}
    ShopTonBuy = 1004                            // 是否花费{1} <img src='ui://item/Ton'/>购买？
    FunctionNotOpen = 1005                       // 敬请期待！
    EggRecoveryCard = 1006                       // 是否使用1张空蛋挽回卡重置？（剩余空蛋挽回卡数量：[color=#FF0000]{1}[/color]）
    EggRecoveryCardNotEnough = 1007              // 糟糕，这个蛋是空的！是否花费{1} <img src='ui://item/zs'/>复原此蛋？
    BuyEggCollectionCard = 1008                  // 花费｛1｝<img src='ui://item/zs02'/>购买｛2｝天自动取蛋卡？
    EggAutoCollection = 1009                     // 哇！使用自动收蛋卡收集了{0}个蛋！
    GetEggAutoCollection = 1010                  // 成功购买自动收蛋卡{1}天
    GetDeluxePass = 1011                         // 成功购买豪华版通行证
    GetCheckInCard = 1012                        // 成功购买签到卡
    ResigningTips = 1013                         // 是否花费{1} <img src='ui://item/zs02'/>进行补签？你已补签{2}次（最多补签7次）
)